name: 'Trigger'
on:
  push:
    branches:
      - main

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.G_PERSONAL }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'bkolad',
              repo: 'child_repo',
              workflow_id: 'workflow.yml',
              ref: 'main'
            })
            console.log(result)
    
      - name: Wait for the other CI
        run: sleep 10s
      
      - uses: actions/checkout@v3
      - name: Test2
        env:
          CI_TRIGGER_ACCESS_TOKEN: ${{ secrets.G_PERSONAL }}
        run: ./github/ci.sh
