name: 'Workflow of Parent REPO'

on:
  push:
    branches:
      - main

jobs: 
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.G_PERSONAL }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'bkolad',
              repo: 'child_repo',
              workflow_id: 'workflow.yaml',
              ref: 'main'
            })
