name: 'Workflow of Parent REPO'

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main

jobs: 
  trigger_workflow:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
#      - name: Deploy
#        run: |
#          curl -X POST 'https://api.github.com/repos/bkolad/child_repo/actions/workflows/workflow.yaml/dispatches' \
#          -H 'Accept: application/vnd.github.everest-preview+json' \
#          -H 'Authorization: Bearer ${{ secrets.G_PERSONAL }}' \
#          -d '{"ref":"main"}'
          
   
