name: 'Workflow of Parent REPO'

on:
  push:
    branches:
      - main

jobs: 
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          curl -X POST 'https://api.github.com/repos/bkolad/child_repo/actions/workflows/workflow.yml/dispatches' \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Authorization: Bearer ${{ secrets.PERSONAL }}' \
          -d '{"ref":"mains"}'

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'bkolad',
              repo: 'child_repo',
              workflow_id: 'workflow.yml',
              ref: 'main'
            })
      - name: Echo Workflow name
        shell: bash
        run: |
          echo "I am Workflow of Parent REPO"
      - name: Trigger child repo workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: bkolad
          repo:  child_repo
          github_token: ${{ secrets.PERSONAL  }}
          workflow_file_name: workflow.yml
          ref: main
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true